// methods/build.rs — RISC Zero Guest Compilation
//
// This script compiles the Guest code (methods/guest/src/main.rs) into
// a RISC-V ELF binary and generates a deterministic ImageID.
//
// The ImageID is a cryptographic fingerprint of the 124M supply law.
// If the Guest code changes by even one byte, the ImageID changes and
// proofs generated by the old law will be rejected by the network.

fn main() {
    risc0_build::embed_methods();
}
